//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaReservasRestaurante.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RestauranteEntities : DbContext
    {
        public DB_RestauranteEntities()
            : base("name=DB_RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriasMesa> CategoriasMesa { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Mesas> Mesas { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
